name: CI

on: 
  push:
  pull_request:

jobs:
  run-tests:
    strategy: 
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: 
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
          - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"
      
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # Allow pre-release versions like 3.12-dev
          include-prereleases: true

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install pytest . 

      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings

      - name: Display Python version
        run: python --version
